var l;l||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da="./this.program",ea=(a,b)=>{throw b;},fa="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?fa=__filename:ba&&(fa=self.location.href);var ha="",ia,ja;
if(ca){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=l);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var la=console.log.bind(console),m=console.error.bind(console),q,ma=!1,na,ka=a=>a.startsWith("file://"),oa,r,t,pa,B,C,E,qa,ra,sa,ta,F=0,G=null;
function ua(a){l.onAbort?.(a);a="Aborted("+a+")";m(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;async function wa(a){if(!q)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==va&&q)a=new Uint8Array(q);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;if(!q&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(l)},Ba=[],Ca=[],Da=()=>{var a=l.preRun.shift();Ca.push(a)},Ea=!0;class Fa{constructor(a){this.T=a-24}}var Ga=0,Ha=0,H=a=>{for(var b="";;){var c=t[a++];if(!c)return b;b+=String.fromCharCode(c)}},I={},J={},Ia={},K=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ja=a=>{throw new K(a);};
function Ka(a,b,c={}){var d=b.name;if(!a)throw new K(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.Sa)return;throw new K(`Cannot register type '${d}' twice`);}J[a]=b;delete Ia[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function M(a,b,c={}){return Ka(a,b,c)}
var La=(a,b,c)=>{switch(b){case 1:return c?d=>r[d]:d=>t[d];case 2:return c?d=>pa[d>>1]:d=>B[d>>1];case 4:return c?d=>C[d>>2]:d=>E[d>>2];case 8:return c?d=>sa[d>>3]:d=>ta[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ma=a=>{throw new K(a.N.U.R.name+" instance already deleted");},Na=!1,Oa=()=>{},Pa=a=>{if("undefined"===typeof FinalizationRegistry)return Pa=b=>b,a;Na=new FinalizationRegistry(b=>{b=b.N;--b.count.value;0===b.count.value&&(b.Y?b.aa.ka(b.Y):b.U.R.ka(b.T))});
Pa=b=>{var c=b.N;c.Y&&Na.register(b,{N:c},b);return b};Oa=b=>{Na.unregister(b)};return Pa(a)},Qa=[];function Ra(){}
var Sa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ta={},Ua=(a,b,c)=>{if(void 0===a[b].X){var d=a[b];a[b]=function(...e){if(!a[b].X.hasOwnProperty(e.length))throw new K(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].X})!`);return a[b].X[e.length].apply(this,e)};a[b].X=[];a[b].X[d.pa]=d}},Va=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].X&&void 0!==l[a].X[c])throw new K(`Cannot register public name '${a}' twice`);Ua(l,a,a);if(l[a].X.hasOwnProperty(c))throw new K(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[a].X[c]=b}else l[a]=b,l[a].pa=c},Wa=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Xa(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.ja=c;this.ka=d;this.Z=e;this.Qa=f;this.sa=g;this.Pa=h;this.Wa=[]}
var Ya=(a,b,c)=>{for(;b!==c;){if(!b.sa)throw new K(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.sa(a);b=b.Z}return a},Za=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function $a(a,b){if(null===b){if(this.Ca)throw new K(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new K(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.N.T)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ya(b.N.T,b.N.U.R,this.R)}
function ab(a,b){if(null===b){if(this.Ca)throw new K(`null is not a valid ${this.name}`);if(this.va){var c=this.Xa();null!==a&&a.push(this.ka,c);return c}return 0}if(!b||!b.N)throw new K(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.N.T)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ua&&b.N.U.ua)throw new K(`Cannot convert argument of type ${b.N.aa?b.N.aa.name:b.N.U.name} to parameter type ${this.name}`);c=Ya(b.N.T,b.N.U.R,this.R);if(this.va){if(void 0===
b.N.Y)throw new K("Passing raw pointer to smart pointer is illegal");switch(this.Za){case 0:if(b.N.aa===this)c=b.N.Y;else throw new K(`Cannot convert argument of type ${b.N.aa?b.N.aa.name:b.N.U.name} to parameter type ${this.name}`);break;case 1:c=b.N.Y;break;case 2:if(b.N.aa===this)c=b.N.Y;else{var d=b.clone();c=this.Ya(c,bb(()=>d["delete"]()));null!==a&&a.push(this.ka,c)}break;default:throw new K("Unsupporting sharing policy");}}return c}
function cb(a,b){if(null===b){if(this.Ca)throw new K(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new K(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.N.T)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.N.U.ua)throw new K(`Cannot convert argument of type ${b.N.U.name} to parameter type ${this.name}`);return Ya(b.N.T,b.N.U.R,this.R)}function db(a){return this.W(E[a>>2])}
var eb=(a,b,c)=>{if(b===c)return a;if(void 0===c.Z)return null;a=eb(a,b,c.Z);return null===a?null:c.Pa(a)},gb={},hb=(a,b)=>{if(void 0===b)throw new K("ptr should not be undefined");for(;a.Z;)b=a.sa(b),a=a.Z;return gb[b]},ib=class extends Error{constructor(a){super(a);this.name="InternalError"}},jb=(a,b)=>{if(!b.U||!b.T)throw new ib("makeClassHandle requires ptr and ptrType");if(!!b.aa!==!!b.Y)throw new ib("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Pa(Object.create(a,
{N:{value:b,writable:!0}}))};function kb(a,b,c,d,e,f,g,h,p,k,n){this.name=a;this.R=b;this.Ca=c;this.ua=d;this.va=e;this.Va=f;this.Za=g;this.Na=h;this.Xa=p;this.Ya=k;this.ka=n;e||void 0!==b.Z?this.$=ab:(this.$=d?$a:cb,this.ba=null)}
var lb=(a,b,c)=>{if(!l.hasOwnProperty(a))throw new ib("Replacing nonexistent public symbol");void 0!==l[a].X&&void 0!==c?l[a].X[c]=b:(l[a]=b,l[a].pa=c)},mb=[],nb,N=(a,b)=>{a=H(a);var c;(c=mb[b])||(mb[b]=c=nb.get(b));if("function"!=typeof c)throw new K(`unknown function pointer with signature ${a}: ${b}`);return c};class ob extends Error{}
var qb=a=>{a=pb(a);var b=H(a);O(a);return b},P=(a,b)=>{function c(f){e[f]||J[f]||(Ia[f]?Ia[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ob(`${a}: `+d.map(qb).join([", "]));},Q=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new ib("Mismatched type converter count");for(var p=0;p<a.length;++p)M(a[p],h[p])}a.forEach(h=>Ia[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,p)=>{J.hasOwnProperty(h)?e[p]=J[h]:(f.push(h),I.hasOwnProperty(h)||(I[h]=[]),I[h].push(()=>
{e[p]=J[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},rb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},sb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function tb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ba)return!0;return!1}
function ub(a,b,c,d,e,f){var g=b.length;if(2>g)throw new K("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,p=tb(b);c=!b[0].Ia;var k=b[0],n=b[1];d=[a,Ja,d,e,sb,k.W.bind(k),n?.$.bind(n)];for(e=2;e<g;++e)k=b[e],d.push(k.$.bind(k));if(!p)for(e=h?1:2;e<b.length;++e)null!==b[e].ba&&d.push(b[e].ba);p=tb(b);e=b.length-2;n=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),k.push(`arg${g}Wired`);n=n.join(",");k=k.join(",");n=`return function (${n}) {\n`;
p&&(n+="var destructors = [];\n");var u=p?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(n+=`var thisWired = toClassParamWire(${u}, this);\n`);for(g=0;g<e;++g){var x=`toArg${g}Wire`;n+=`var arg${g}Wired = ${x}(${u}, arg${g});\n`;v.push(x)}n+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(p)n+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].ba&&(n+=`${f}_dtor(${f});\n`,
v.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(v,n+"}\n"))(...d);return Sa(a,b)}
var vb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},wb=(a,b,c)=>{if(!(a instanceof Object))throw new K(`${c} with invalid "this": ${a}`);if(!(a instanceof b.R.constructor))throw new K(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.N.T)throw new K(`cannot call emscripten binding method ${c} on deleted object`);return Ya(a.N.T,a.N.U.R,b.R)},xb=[],R=[0,1,,1,null,1,!0,1,!1,1],yb=a=>{9<a&&0===--R[a+1]&&(R[a]=void 0,xb.push(a))},zb=a=>{if(!a)throw new K(`Cannot use deleted val. handle = ${a}`);
return R[a]},bb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=xb.pop()||R.length;R[b]=a;R[b+1]=1;return b}},Ab={name:"emscripten::val",W:a=>{var b=zb(a);yb(a);return b},$:(a,b)=>bb(b),ha:db,ba:null},Bb=(a,b)=>{switch(b){case 4:return function(c){return this.W(qa[c>>2])};case 8:return function(c){return this.W(ra[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Cb=Object.assign({optional:!0},Ab),S=(a,b,c,d)=>{if(!(0<
d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Eb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Fb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Gb=(a,b=0,c,d)=>{c=Fb(a,b,c,d);if(16<c-b&&a.buffer&&Eb)return Eb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},Hb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Ib=(a,b,c)=>{a>>=1;b=Fb(B,a,b/2,c);if(16<b-a&&Hb)return Hb.decode(B.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(B[a]);return c},Jb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)pa[b>>1]=a.charCodeAt(e),b+=2;pa[b>>1]=0;return b-d},Kb=a=>2*a.length,Lb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;
d+=String.fromCodePoint(f)}return d},Mb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Nb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Ob=0,Pb=[],Qb=a=>{var b=Pb.length;Pb.push(a);return b},Rb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+4*d>>2],g=J[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${qb(f)}`,new K(a);c[e]=
g}return c},Sb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=bb(d));return a},Tb={},Ub=a=>{var b=Tb[a];return void 0===b?H(a):b},Vb={},Wb=a=>{na=a;Ea||0<Ob||(l.onExit?.(a),ma=!0);ea(a,new za(a))},Xb=a=>{if(!ma)try{if(a(),!(Ea||0<Ob))try{na=a=na,Wb(a)}catch(b){b instanceof za||"unwind"==b||ea(1,b)}}catch(b){b instanceof za||"unwind"==b||ea(1,b)}},Yb={},$b=()=>{if(!Zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||
"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Yb)void 0===Yb[b]?delete a[b]:a[b]=Yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Zb=c}return Zb},Zb,bc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},cc=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=bc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},dc=a=>{var b=
/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},ec=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},fc=a=>{(fc=ec())(a)},gc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=bc(b.split("/").filter(e=>
!!e),!c).join("/");return(c?"/":"")+b||"."},hc=[],ic=[];function jc(a,b){ic[a]={input:[],output:[],oa:b};kc(a,lc)}
var lc={open(a){var b=ic[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close(a){a.tty.oa.fsync(a.tty)},fsync(a){a.tty.oa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.oa.Ha)throw new T(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.oa.Ha(a.tty)}catch(h){throw new T(29);}if(void 0===g&&0===e)throw new T(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.oa.Da)throw new T(60);try{for(var e=0;e<d;e++)a.tty.oa.Da(a.tty,b[c+e])}catch(f){throw new T(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},mc={Ha(){a:{if(!hc.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Db(a)+1);a=S(a,b,0,b.length);b.length=a;hc=b}a=hc.shift()}return a},Da(a,b){null===
b||10===b?(la(Gb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(la(Gb(a.output)),a.output=[])},jb(){return{eb:25856,gb:5,cb:191,fb:35387,bb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},kb(){return 0},lb(){return[24,80]}},nc={Da(a,b){null===b||10===b?(m(Gb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(m(Gb(a.output)),a.output=[])}},U={ea:null,ga(){return U.createNode(null,"/",16895,0)},createNode(a,b,c,
d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.ea||(U.ea={dir:{node:{ia:U.P.ia,fa:U.P.fa,lookup:U.P.lookup,wa:U.P.wa,rename:U.P.rename,unlink:U.P.unlink,rmdir:U.P.rmdir,readdir:U.P.readdir,symlink:U.P.symlink},stream:{da:U.S.da}},file:{node:{ia:U.P.ia,fa:U.P.fa},stream:{da:U.S.da,read:U.S.read,write:U.S.write,Ka:U.S.Ka,Ma:U.S.Ma}},link:{node:{ia:U.P.ia,fa:U.P.fa,readlink:U.P.readlink},stream:{}},Fa:{node:{ia:U.P.ia,fa:U.P.fa},stream:oc}});c=pc(a,b,c,d);16384===(c.mode&61440)?(c.P=U.ea.dir.node,
c.S=U.ea.dir.stream,c.O={}):32768===(c.mode&61440)?(c.P=U.ea.file.node,c.S=U.ea.file.stream,c.V=0,c.O=null):40960===(c.mode&61440)?(c.P=U.ea.link.node,c.S=U.ea.link.stream):8192===(c.mode&61440)&&(c.P=U.ea.Fa.node,c.S=U.ea.Fa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.O[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},ib(a){return a.O?a.O.subarray?a.O.subarray(0,a.V):new Uint8Array(a.O):new Uint8Array(0)},P:{ia(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;
b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.V:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},fa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.V!=b&&(0==b?(a.O=null,a.V=0):(c=a.O,a.O=new Uint8Array(b),c&&a.O.set(c.subarray(0,Math.min(b,a.V))),a.V=
b)))},lookup(){U.ya||(U.ya=new T(44),U.ya.stack="<generic error, no stack>");throw U.ya;},wa(a,b,c,d){return U.createNode(a,b,c,d)},rename(a,b,c){try{var d=qc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.O)throw new T(55);e=rc(d.parent.id,d.name);if(V[e]===d)V[e]=d.na;else for(e=V[e];e;){if(e.na===d){e.na=d.na;break}e=e.na}}delete a.parent.O[a.name];b.O[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.O[b];a.ctime=a.mtime=Date.now()},rmdir(a,
b){var c=qc(a,b),d;for(d in c.O)throw new T(55);delete a.O[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.O)]},symlink(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},S:{read(a,b,c,d,e){var f=a.node.O;if(e>=a.node.V)return 0;a=Math.min(a.node.V-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=
Date.now();if(b.subarray&&(!a.O||a.O.subarray)){if(f)return a.O=b.subarray(c,c+d),a.V=d;if(0===a.V&&0===e)return a.O=b.slice(c,c+d),a.V=d;if(e+d<=a.V)return a.O.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.O?a.O.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.O,a.O=new Uint8Array(f),0<a.V&&a.O.set(g.subarray(0,a.V),0));if(a.O.subarray&&b.subarray)a.O.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.O[e+f]=b[c+f];a.V=Math.max(a.V,e+d);return d},da(a,b,c){1===c?b+=a.position:
2===c&&32768===(a.node.mode&61440)&&(b+=a.node.V);if(0>b)throw new T(28);return b},Ka(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.O;if(e&2||!a||a.buffer!==r.buffer){d=!0;ua();e=void 0;if(!e)throw new T(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{T:e,ab:d}},Ma(a,b,c,d){U.S.write(a,b,0,d,c,!1);return 0}}},sc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},tc=null,uc={},vc=[],
wc=1,V=null,xc=!1,yc=!0,zc={},T=class{name="ErrnoError";constructor(a){this.ma=a}},Ac=class{ta={};node=null;get flags(){return this.ta.flags}set flags(a){this.ta.flags=a}get position(){return this.ta.position}set position(a){this.ta.position=a}},Bc=class{P={};S={};xa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ga=a.ga;this.id=wc++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=
-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function W(a,b={}){if(!a)throw new T(44);b.Aa??(b.Aa=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=tc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=dc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=cc(e+"/"+a[f]);try{d=qc(d,a[f])}catch(h){if(44===h?.ma&&g&&b.Ua)return{path:e};throw h;}!d.xa||g&&!b.Aa||(d=d.xa.root);if(40960===(d.mode&61440)&&(!g||b.za)){if(!d.P.readlink)throw new T(52);
d=d.P.readlink(d);"/"===d.charAt(0)||(d=dc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new T(32);}function rc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%V.length}function qc(a,b){var c=16384===(a.mode&61440)?(c=Cc(a,"x"))?c:a.P.lookup?0:2:54;if(c)throw new T(c);for(c=V[rc(a.id,b)];c;c=c.na){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.P.lookup(a,b)}
function pc(a,b,c,d){a=new Bc(a,b,c,d);b=rc(a.parent.id,a.name);a.na=V[b];return V[b]=a}function Dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cc(a,b){if(yc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ec(a,b){if(16384!==(a.mode&61440))return 54;try{return qc(a,b),20}catch(c){}return Cc(a,"wx")}function Fc(a){a=vc[a];if(!a)throw new T(8);return a}
function Gc(a,b){var c=null?.S.fa,d=c?null:a;c??=a.P.fa;if(!c)throw new T(63);c(d,b)}var oc={open(a){a.S=uc[a.node.rdev].S;a.S.open?.(a)},da(){throw new T(70);}};function kc(a,b){uc[a]={S:b}}function Hc(a,b){var c="/"===b;if(c&&tc)throw new T(10);if(!c&&b){var d=W(b,{Aa:!1});b=d.path;d=d.node;if(d.xa)throw new T(10);if(16384!==(d.mode&61440))throw new T(54);}b={type:a,mb:{},La:b,Ta:[]};a=a.ga(b);a.ga=b;b.root=a;c?tc=a:d&&(d.xa=b,d.ga&&d.ga.Ta.push(b))}
function Ic(a,b,c){var d=W(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new T(28);if("."===a||".."===a)throw new T(20);var e=Ec(d,a);if(e)throw new T(e);if(!d.P.wa)throw new T(63);return d.P.wa(d,a,b,c)}function X(a){return Ic(a,16895,0)}function Jc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ic(a,b|8192,c)}
function Kc(a,b){if(!gc(a))throw new T(44);var c=W(b,{parent:!0}).node;if(!c)throw new T(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ec(c,b);if(d)throw new T(d);if(!c.P.symlink)throw new T(63);c.P.symlink(c,b,a)}
function Lc(a,b){if(""===a)throw new T(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=W(a,{za:!(b&131072),Ua:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new T(20);}else{if(e)throw new T(31);d=Ic(a,c|511,0);f=!0}if(!d)throw new T(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new T(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Dc(b)||b&576)?31:Cc(d,Dc(b)):44))throw new T(e);if(b&512&&!f){e=d;e="string"==typeof e?W(e,{za:!0}).node:e;if(16384===(e.mode&61440))throw new T(31);if(32768!==(e.mode&61440))throw new T(28);var g=Cc(e,"w");if(g)throw new T(g);Gc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.ga.La;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h={node:d,path:h,flags:b,
seekable:!0,position:0,S:d.S,$a:[],error:!1};e=-1;h=Object.assign(new Ac,h);if(-1==e)a:{for(e=0;4096>=e;e++)if(!vc[e])break a;throw new T(33);}h.fd=e;vc[e]=h;h.S.open&&h.S.open(h);f&&(c&=511,d="string"==typeof d?W(d,{za:!0}).node:d,Gc(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),hb:void 0}));!l.logReadFiles||b&1||a in zc||(zc[a]=1)}function Mc(a,b,c){if(null===a.fd)throw new T(8);if(!a.seekable||!a.S.da)throw new T(70);if(0!=c&&1!=c&&2!=c)throw new T(28);a.position=a.S.da(a,b,c);a.$a=[]}
function Y(a,b,c){a=cc("/dev/"+a);var d=sc(!!b,!!c);Y.Ja??(Y.Ja=64);var e=Y.Ja++<<8|0;kc(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,p){for(var k=0,n=0;n<p;n++){try{var u=b()}catch(v){throw new T(29);}if(void 0===u&&0===k)throw new T(6);if(null===u||void 0===u)break;k++;g[h+n]=u}k&&(f.node.atime=Date.now());return k},write(f,g,h,p){for(var k=0;k<p;k++)try{c(g[h+k])}catch(n){throw new T(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return k}});Jc(a,d,e)}var Nc={};
(()=>{let a=Ra.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Ra&&c instanceof Ra))return!1;var d=this.N.U.R,e=this.N.T;c.N=c.N;var f=c.N.U.R;for(c=c.N.T;d.Z;)e=d.sa(e),d=d.Z;for(;f.Z;)c=f.sa(c),f=f.Z;return d===f&&e===c},clone:function(){this.N.T||Ma(this);if(this.N.ra)return this.N.count.value+=1,this;var c=Pa,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.N;c=c(e.call(d,f,{N:{value:{count:g.count,qa:g.qa,ra:g.ra,T:g.T,U:g.U,Y:g.Y,aa:g.aa}}}));c.N.count.value+=1;
c.N.qa=!1;return c},["delete"](){this.N.T||Ma(this);if(this.N.qa&&!this.N.ra)throw new K("Object already scheduled for deletion");Oa(this);var c=this.N;--c.count.value;0===c.count.value&&(c.Y?c.aa.ka(c.Y):c.U.R.ka(c.T));this.N.ra||(this.N.Y=void 0,this.N.T=void 0)},isDeleted:function(){return!this.N.T},deleteLater:function(){this.N.T||Ma(this);if(this.N.qa&&!this.N.ra)throw new K("Object already scheduled for deletion");Qa.push(this);this.N.qa=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(kb.prototype,{Ra(a){this.Na&&(a=this.Na(a));return a},Ga(a){this.ka?.(a)},ha:db,W:function(a){function b(){return this.va?jb(this.R.ja,{U:this.Va,T:c,aa:this,Y:a}):jb(this.R.ja,{U:this,T:a})}var c=this.Ra(a);if(!c)return this.Ga(a),null;var d=hb(this.R,c);if(void 0!==d){if(0===d.N.count.value)return d.N.T=c,d.N.Y=a,d.clone();d=d.clone();this.Ga(a);return d}d=this.R.Qa(c);d=Ta[d];if(!d)return b.call(this);d=this.ua?d.Oa:d.pointerType;var e=eb(c,this.R,d.R);return null===e?b.call(this):
this.va?jb(d.R.ja,{U:d,T:e,aa:this,Y:a}):jb(d.R.ja,{U:d,T:e})}});V=Array(4096);Hc(U,"/");X("/tmp");X("/home");X("/home/web_user");(function(){X("/dev");kc(259,{read:()=>0,write:(d,e,f,g)=>g,da:()=>0});Jc("/dev/null",259);jc(1280,mc);jc(1536,nc);Jc("/dev/tty",1280);Jc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(fc(a),b=a.byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Hc({ga(){var b=pc(a,"fd",16895,73);b.S={da:U.S.da};b.P={lookup(c,d){c=+d;var e=Fc(c);c={parent:null,ga:{La:"fake"},P:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(vc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();l.noExitRuntime&&(Ea=l.noExitRuntime);l.print&&(la=l.print);l.printErr&&(m=l.printErr);l.wasmBinary&&(q=l.wasmBinary);l.thisProgram&&(da=l.thisProgram);
var pb,Oc,Pc,O,Qc={j:(a,b,c)=>{var d=new Fa(a);E[d.T+16>>2]=0;E[d.T+4>>2]=b;E[d.T+8>>2]=c;Ga=a;Ha++;throw Ga;},x:()=>ua(""),h:(a,b,c,d,e)=>{b=H(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}M(a,{name:b,W:f,$:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},ha:La(b,c,!d),ba:null})},l:(a,b,c,d)=>{b=H(b);M(a,{name:b,W:function(e){return!!e},$:function(e,f){return f?c:d},ha:function(e){return this.W(t[e])},ba:null})},i:(a,b,c,d,e,f,g,h,p,k,n,u,v)=>{n=H(n);f=N(e,f);h&&=N(g,
h);k&&=N(p,k);v=N(u,v);var x=Wa(n);Va(x,function(){P(`Cannot construct ${n} due to unbound types`,[d])});Q([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var z=w.R;var A=z.ja}else A=Ra.prototype;w=Sa(n,function(...fb){if(Object.getPrototypeOf(this)!==D)throw new K(`Use 'new' to construct ${n}`);if(void 0===y.la)throw new K(`${n} has no accessible constructor`);var ac=y.la[fb.length];if(void 0===ac)throw new K(`Tried to invoke ctor of ${n} with invalid number of parameters (${fb.length}) - expected (${Object.keys(y.la).toString()}) parameters instead!`);
return ac.apply(this,fb)});var D=Object.create(A,{constructor:{value:w}});w.prototype=D;var y=new Xa(n,w,D,v,z,f,h,k);if(y.Z){var L;(L=y.Z).Ea??(L.Ea=[]);y.Z.Ea.push(y)}z=new kb(n,y,!0,!1,!1);L=new kb(n+"*",y,!1,!1,!1);A=new kb(n+" const*",y,!1,!0,!1);Ta[a]={pointerType:L,Oa:A};lb(x,w);return[z,L,A]})},D:(a,b,c,d,e,f)=>{var g=rb(b,c);e=N(d,e);Q([],[a],h=>{h=h[0];var p=`constructor ${h.name}`;void 0===h.R.la&&(h.R.la=[]);if(void 0!==h.R.la[b-1])throw new K(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.R.la[b-1]=()=>{P(`Cannot construct ${h.name} due to unbound types`,g)};Q([],g,k=>{k.splice(1,0,null);h.R.la[b-1]=ub(p,k,null,e,f);return[]});return[]})},c:(a,b,c,d,e,f,g,h,p)=>{var k=rb(c,d);b=H(b);b=vb(b);f=N(e,f);Q([],[a],n=>{function u(){P(`Cannot call ${v} due to unbound types`,k)}n=n[0];var v=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&n.R.Wa.push(b);
var x=n.R.ja,w=x[b];void 0===w||void 0===w.X&&w.className!==n.name&&w.pa===c-2?(u.pa=c-2,u.className=n.name,x[b]=u):(Ua(x,b,v),x[b].X[c-2]=u);Q([],k,z=>{z=ub(v,z,n,f,g,p);void 0===x[b].X?(z.pa=c-2,x[b]=z):x[b].X[c-2]=z;return[]});return[]})},e:(a,b,c,d,e,f,g,h,p,k)=>{b=H(b);e=N(d,e);Q([],[a],n=>{n=n[0];var u=`${n.name}.${b}`,v={get(){P(`Cannot access ${u} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};v.set=p?()=>P(`Cannot access ${u} due to unbound types`,[c,g]):()=>{throw new K(u+
" is a read-only property");};Object.defineProperty(n.R.ja,b,v);Q([],p?[c,g]:[c],x=>{var w=x[0],z={get(){var D=wb(this,n,u+" getter");return w.W(e(f,D))},enumerable:!0};if(p){p=N(h,p);var A=x[1];z.set=function(D){var y=wb(this,n,u+" setter"),L=[];p(k,y,A.$(L,D));sb(L)}}Object.defineProperty(n.R.ja,b,z);return[]});return[]})},F:a=>M(a,Ab),g:(a,b,c)=>{b=H(b);M(a,{name:b,W:d=>d,$:(d,e)=>e,ha:Bb(b,c),ba:null})},f:(a,b,c,d,e,f,g)=>{var h=rb(b,c);a=H(a);a=vb(a);e=N(d,e);Va(a,function(){P(`Cannot call ${a} due to unbound types`,
h)},b-1);Q([],h,p=>{p=[p[0],null].concat(p.slice(1));lb(a,ub(a,p,null,e,f,g),b-1);return[]})},b:(a,b,c,d,e)=>{b=H(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}M(a,{name:b,W:f,$:(h,p)=>p,ha:La(b,c,0!==d),ba:null})},a:(a,b,c)=>{function d(f){return new e(r.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=H(c);M(a,{name:c,W:d,ha:d},{Sa:!0})},E:a=>{M(a,Cb)},k:(a,b)=>{b=H(b);M(a,
{name:b,W(c){var d=(d=c+4)?Gb(t,d,E[c>>2],!0):"";O(c);return d},$(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new K("Cannot pass non-string to std::string");var f=e?Db(d):d.length;var g=Pc(4+f+1),h=g+4;E[g>>2]=f;e?S(d,t,h,f+1):t.set(d,h);null!==c&&c.push(O,g);return g},ha:db,ba(c){O(c)}})},d:(a,b,c)=>{c=H(c);if(2===b){var d=Ib;var e=Jb;var f=Kb}else d=Lb,e=Mb,f=Nb;M(a,{name:c,W:g=>{var h=d(g+4,E[g>>2]*b,
!0);O(g);return h},$:(g,h)=>{if("string"!=typeof h)throw new K(`Cannot pass non-string to C++ string type ${c}`);var p=f(h),k=Pc(4+p+b);E[k>>2]=p/b;e(h,k+4,p+b);null!==g&&g.push(O,k);return k},ha:db,ba(g){O(g)}})},m:(a,b)=>{b=H(b);M(a,{Ia:!0,name:b,W:()=>{},$:()=>{}})},q:()=>{Ea=!1;Ob=0},r:(a,b,c)=>{var [d,...e]=Rb(a,b);b=d.$.bind(d);var f=e.map(p=>p.ha.bind(p));a--;var g={toValue:zb};a=f.map((p,k)=>{var n=`argFromPtr${k}`;g[n]=p;return`${n}(args${k?"+"+8*k:""})`});switch(c){case 0:var h="toValue(handle)";
break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Ub,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.Ia||(g.toReturnWire=b,g.emval_returnValue=Sb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;return Qb(Sa(h,c))},o:(a,b,c,d,e)=>Pb[a](b,c,
d,e),n:a=>{var b=zb(a);sb(b);yb(a)},s:(a,b)=>{Vb[a]&&(clearTimeout(Vb[a].id),delete Vb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Vb[a];Xb(()=>Oc(a,performance.now()))},b);Vb[a]={id:c,nb:b};return 0},u:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);C[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};
a=b(f);b=b(e);e<f?(S(a,t,c,17),S(b,t,d,17)):(S(a,t,d,17),S(b,t,c,17))},C:()=>{ua("OOM")},v:(a,b)=>{var c=0,d=0,e;for(e of $b()){var f=b+c;E[a+d>>2]=f;c+=S(e,t,f,Infinity)+1;d+=4}return 0},w:(a,b)=>{var c=$b();E[a>>2]=c.length;a=0;for(var d of c)a+=Db(d)+1;E[b>>2]=a;return 0},y:function(a){try{var b=Fc(a);if(null===b.fd)throw new T(8);b.Ba&&(b.Ba=null);try{b.S.close&&b.S.close(b)}catch(c){throw c;}finally{vc[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;
return c.ma}},B:function(a,b,c,d){try{a:{var e=Fc(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],p=E[a+4>>2];a+=8;var k=e,n=h,u=p,v=f,x=r;if(0>u||0>v)throw new T(28);if(null===k.fd)throw new T(8);if(1===(k.flags&2097155))throw new T(8);if(16384===(k.node.mode&61440))throw new T(31);if(!k.S.read)throw new T(28);var w="undefined"!=typeof v;if(!w)v=k.position;else if(!k.seekable)throw new T(70);var z=k.S.read(k,x,n,u,v);w||(k.position+=z);var A=z;if(0>A){var D=-1;break a}b+=A;if(A<p)break;"undefined"!=
typeof f&&(f+=A)}D=b}E[d>>2]=D;return 0}catch(y){if("undefined"==typeof Nc||"ErrnoError"!==y.name)throw y;return y.ma}},z:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Fc(a);Mc(e,b,c);sa[d>>3]=BigInt(e.position);e.Ba&&0===b&&0===c&&(e.Ba=null);return 0}catch(f){if("undefined"==typeof Nc||"ErrnoError"!==f.name)throw f;return f.ma}},A:function(a,b,c,d){try{a:{var e=Fc(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],p=E[a+4>>2];a+=8;var k=e,n=
h,u=p,v=f,x=r;if(0>u||0>v)throw new T(28);if(null===k.fd)throw new T(8);if(0===(k.flags&2097155))throw new T(8);if(16384===(k.node.mode&61440))throw new T(31);if(!k.S.write)throw new T(28);k.seekable&&k.flags&1024&&Mc(k,0,2);var w="undefined"!=typeof v;if(!w)v=k.position;else if(!k.seekable)throw new T(70);var z=k.S.write(k,x,n,u,v,void 0);w||(k.position+=z);var A=z;if(0>A){var D=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&(f+=A)}D=b}E[d>>2]=D;return 0}catch(y){if("undefined"==typeof Nc||
"ErrnoError"!==y.name)throw y;return y.ma}},p:Wb,t:function(a,b){try{return fc(t.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;return c.ma}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.G;c=oa.buffer;r=new Int8Array(c);pa=new Int16Array(c);t=new Uint8Array(c);B=new Uint16Array(c);C=new Int32Array(c);E=new Uint32Array(c);qa=new Float32Array(c);ra=new Float64Array(c);sa=new BigInt64Array(c);ta=new BigUint64Array(c);nb=Z.L;c=Z;pb=c.I;Oc=c.J;Pc=c.K;O=c.M;F--;l.monitorRunDependencies?.(F);0==F&&G&&(c=G,G=null,c());return Z}F++;l.monitorRunDependencies?.(F);var b={a:Qc};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(b,(d,
e)=>{c(a(d,e))})});va??=l.locateFile?l.locateFile("hillclimbing.wasm",ha):ha+"hillclimbing.wasm";return a((await ya(b)).instance)})();
function Rc(){function a(){l.calledRun=!0;if(!ma){if(!l.noFSInit&&!xc){var b,c;xc=!0;b??=l.stdin;c??=l.stdout;d??=l.stderr;b?Y("stdin",b):Kc("/dev/tty","/dev/stdin");c?Y("stdout",null,c):Kc("/dev/tty","/dev/stdout");d?Y("stderr",null,d):Kc("/dev/tty1","/dev/stderr");Lc("/dev/stdin",0);Lc("/dev/stdout",1);Lc("/dev/stderr",1)}Z.H();yc=!1;l.onRuntimeInitialized?.();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var d=l.postRun.shift();Ba.push(d)}Aa(Ba)}}if(0<
F)G=Rc;else{if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)Da();Aa(Ca);0<F?G=Rc:l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);a()},1)):a()}}if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();Rc();
