var k;k||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da="./this.program",ea=(a,b)=>{throw b;},fa="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?fa=__filename:ba&&(fa=self.location.href);var ha="",ia,ja;
if(ca){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var la=console.log.bind(console),m=console.error.bind(console),q,ma=!1,na,ka=a=>a.startsWith("file://"),oa,r,t,pa,B,C,E,qa,ra,sa,ta,F=0,ua=null;
function va(a){k.onAbort?.(a);a="Aborted("+a+")";m(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var wa;async function xa(a){if(!q)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==wa&&q)a=new Uint8Array(q);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),va(d)}}async function za(a){var b=wa;if(!q&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return ya(b,a)}
class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ba=a=>{for(;0<a.length;)a.shift()(k)},Ca=[],Da=[],Ea=()=>{var a=k.preRun.shift();Da.push(a)},Fa=!0;class Ga{constructor(a){this.na=a-24}}var Ha=0,Ia=0,G=a=>{for(var b="";;){var c=t[a++];if(!c)return b;b+=String.fromCharCode(c)}},H={},I={},Ja={},J=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ka=a=>{throw new J(a);};
function La(a,b,c={}){var d=b.name;if(!a)throw new J(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.mb)return;throw new J(`Cannot register type '${d}' twice`);}I[a]=b;delete Ja[a];H.hasOwnProperty(a)&&(b=H[a],delete H[a],b.forEach(e=>e()))}function K(a,b,c={}){return La(a,b,c)}
var Ma=(a,b,c)=>{switch(b){case 1:return c?d=>r[d]:d=>t[d];case 2:return c?d=>pa[d>>1]:d=>B[d>>1];case 4:return c?d=>C[d>>2]:d=>E[d>>2];case 8:return c?d=>sa[d>>3]:d=>ta[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Na=a=>{throw new J(a.ia.oa.la.name+" instance already deleted");},Oa=!1,Pa=()=>{},Qa=a=>{if("undefined"===typeof FinalizationRegistry)return Qa=b=>b,a;Oa=new FinalizationRegistry(b=>{b=b.ia;--b.count.value;0===b.count.value&&(b.sa?b.va.Ea(b.sa):b.oa.la.Ea(b.na))});
Qa=b=>{var c=b.ia;c.sa&&Oa.register(b,{ia:c},b);return b};Pa=b=>{Oa.unregister(b)};return Qa(a)},Ra=[];function Sa(){}
var Ta=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ua={},Va=(a,b,c)=>{if(void 0===a[b].ra){var d=a[b];a[b]=function(...e){if(!a[b].ra.hasOwnProperty(e.length))throw new J(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ra})!`);return a[b].ra[e.length].apply(this,e)};a[b].ra=[];a[b].ra[d.Ja]=d}},Wa=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].ra&&void 0!==k[a].ra[c])throw new J(`Cannot register public name '${a}' twice`);Va(k,
a,a);if(k[a].ra.hasOwnProperty(c))throw new J(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].ra[c]=b}else k[a]=b,k[a].Ja=c},Xa=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Ya(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Da=c;this.Ea=d;this.ta=e;this.kb=f;this.Ma=g;this.jb=h;this.qb=[]}
var Za=(a,b,c)=>{for(;b!==c;){if(!b.Ma)throw new J(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Ma(a);b=b.ta}return a},$a=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function ab(a,b){if(null===b){if(this.Wa)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.ia)throw new J(`Cannot pass "${$a(b)}" as a ${this.name}`);if(!b.ia.na)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);return Za(b.ia.na,b.ia.oa.la,this.la)}
function bb(a,b){if(null===b){if(this.Wa)throw new J(`null is not a valid ${this.name}`);if(this.Pa){var c=this.rb();null!==a&&a.push(this.Ea,c);return c}return 0}if(!b||!b.ia)throw new J(`Cannot pass "${$a(b)}" as a ${this.name}`);if(!b.ia.na)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Oa&&b.ia.oa.Oa)throw new J(`Cannot convert argument of type ${b.ia.va?b.ia.va.name:b.ia.oa.name} to parameter type ${this.name}`);c=Za(b.ia.na,b.ia.oa.la,this.la);if(this.Pa){if(void 0===
b.ia.sa)throw new J("Passing raw pointer to smart pointer is illegal");switch(this.tb){case 0:if(b.ia.va===this)c=b.ia.sa;else throw new J(`Cannot convert argument of type ${b.ia.va?b.ia.va.name:b.ia.oa.name} to parameter type ${this.name}`);break;case 1:c=b.ia.sa;break;case 2:if(b.ia.va===this)c=b.ia.sa;else{var d=b.clone();c=this.sb(c,cb(()=>d["delete"]()));null!==a&&a.push(this.Ea,c)}break;default:throw new J("Unsupporting sharing policy");}}return c}
function db(a,b){if(null===b){if(this.Wa)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.ia)throw new J(`Cannot pass "${$a(b)}" as a ${this.name}`);if(!b.ia.na)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ia.oa.Oa)throw new J(`Cannot convert argument of type ${b.ia.oa.name} to parameter type ${this.name}`);return Za(b.ia.na,b.ia.oa.la,this.la)}function eb(a){return this.qa(E[a>>2])}
var gb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ta)return null;a=gb(a,b,c.ta);return null===a?null:c.jb(a)},hb={},ib=(a,b)=>{if(void 0===b)throw new J("ptr should not be undefined");for(;a.ta;)b=a.Ma(b),a=a.ta;return hb[b]},jb=class extends Error{constructor(a){super(a);this.name="InternalError"}},kb=(a,b)=>{if(!b.oa||!b.na)throw new jb("makeClassHandle requires ptr and ptrType");if(!!b.va!==!!b.sa)throw new jb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Qa(Object.create(a,
{ia:{value:b,writable:!0}}))};function lb(a,b,c,d,e,f,g,h,p,l,n){this.name=a;this.la=b;this.Wa=c;this.Oa=d;this.Pa=e;this.pb=f;this.tb=g;this.hb=h;this.rb=p;this.sb=l;this.Ea=n;e||void 0!==b.ta?this.ua=bb:(this.ua=d?ab:db,this.wa=null)}
var mb=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new jb("Replacing nonexistent public symbol");void 0!==k[a].ra&&void 0!==c?k[a].ra[c]=b:(k[a]=b,k[a].Ja=c)},nb=[],ob,L=(a,b)=>{a=G(a);var c;(c=nb[b])||(nb[b]=c=ob.get(b));if("function"!=typeof c)throw new J(`unknown function pointer with signature ${a}: ${b}`);return c};class pb extends Error{}
var rb=a=>{a=qb(a);var b=G(a);N(a);return b},O=(a,b)=>{function c(f){e[f]||I[f]||(Ja[f]?Ja[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new pb(`${a}: `+d.map(rb).join([", "]));},P=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new jb("Mismatched type converter count");for(var p=0;p<a.length;++p)K(a[p],h[p])}a.forEach(h=>Ja[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,p)=>{I.hasOwnProperty(h)?e[p]=I[h]:(f.push(h),H.hasOwnProperty(h)||(H[h]=[]),H[h].push(()=>
{e[p]=I[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},sb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},tb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function ub(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].wa)return!0;return!1}
function vb(a,b,c,d,e,f){var g=b.length;if(2>g)throw new J("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,p=ub(b);c=!b[0].bb;var l=b[0],n=b[1];d=[a,Ka,d,e,tb,l.qa.bind(l),n?.ua.bind(n)];for(e=2;e<g;++e)l=b[e],d.push(l.ua.bind(l));if(!p)for(e=h?1:2;e<b.length;++e)null!==b[e].wa&&d.push(b[e].wa);p=ub(b);e=b.length-2;n=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),l.push(`arg${g}Wired`);n=n.join(",");l=l.join(",");
n=`return function (${n}) {\n`;p&&(n+="var destructors = [];\n");var u=p?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(n+=`var thisWired = toClassParamWire(${u}, this);\n`);for(g=0;g<e;++g){var x=`toArg${g}Wire`;n+=`var arg${g}Wired = ${x}(${u}, arg${g});\n`;v.push(x)}n+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(p)n+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].wa&&(n+=`${f}_dtor(${f});\n`,v.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(v,n+"}\n"))(...d);return Ta(a,b)}
var wb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},xb=(a,b,c)=>{if(!(a instanceof Object))throw new J(`${c} with invalid "this": ${a}`);if(!(a instanceof b.la.constructor))throw new J(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.ia.na)throw new J(`cannot call emscripten binding method ${c} on deleted object`);return Za(a.ia.na,a.ia.oa.la,b.la)},yb=[],Q=[0,1,,1,null,1,!0,1,!1,1],zb=a=>{9<a&&0===--Q[a+1]&&(Q[a]=void 0,yb.push(a))},Ab=a=>{if(!a)throw new J(`Cannot use deleted val. handle = ${a}`);
return Q[a]},cb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=yb.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}},Bb={name:"emscripten::val",qa:a=>{var b=Ab(a);zb(a);return b},ua:(a,b)=>cb(b),Ba:eb,wa:null},Cb=(a,b)=>{switch(b){case 4:return function(c){return this.qa(qa[c>>2])};case 8:return function(c){return this.qa(ra[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Db=Object.assign({optional:!0},Bb),R=(a,b,c,d)=>{if(!(0<
d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Eb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Fb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Gb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},S=(a,b=0,c,d)=>{c=Gb(a,b,c,d);if(16<c-b&&a.buffer&&Fb)return Fb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d},Hb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Ib=(a,b,c)=>{a>>=1;b=Gb(B,a,b/2,c);if(16<b-a&&Hb)return Hb.decode(B.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(B[a]);return c},Jb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)pa[b>>1]=a.charCodeAt(e),b+=2;pa[b>>1]=0;return b-d},Kb=a=>2*a.length,Lb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;
d+=String.fromCodePoint(f)}return d},Mb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Nb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Ob=0,Pb=[],Qb=a=>{var b=Pb.length;Pb.push(a);return b},Rb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+4*d>>2],g=I[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${rb(f)}`,new J(a);c[e]=
g}return c},Sb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=cb(d));return a},Tb={},Ub=a=>{var b=Tb[a];return void 0===b?G(a):b},Vb={},Wb=a=>{na=a;Fa||0<Ob||(k.onExit?.(a),ma=!0);ea(a,new Aa(a))},Xb=a=>{if(!ma)try{if(a(),!(Fa||0<Ob))try{na=a=na,Wb(a)}catch(b){b instanceof Aa||"unwind"==b||ea(1,b)}}catch(b){b instanceof Aa||"unwind"==b||ea(1,b)}},Yb={},$b=()=>{if(!Zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||
"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Yb)void 0===Yb[b]?delete a[b]:a[b]=Yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Zb=c}return Zb},Zb,bc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},cc=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=bc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},dc=a=>{var b=
/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},ec=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},fc=a=>{(fc=ec())(a)},gc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=bc(b.split("/").filter(e=>
!!e),!c).join("/");return(c?"/":"")+b||"."},hc=[],ic=[];function jc(a,b){ic[a]={input:[],output:[],Ia:b};kc(a,lc)}
var lc={open(a){var b=ic[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ia.fsync(a.tty)},fsync(a){a.tty.Ia.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ia.ab)throw new T(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ia.ab(a.tty)}catch(h){throw new T(29);}if(void 0===g&&0===e)throw new T(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ia.Xa)throw new T(60);try{for(var e=0;e<d;e++)a.tty.Ia.Xa(a.tty,b[c+e])}catch(f){throw new T(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},mc={ab(){a:{if(!hc.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Eb(a)+1);a=R(a,b,0,b.length);b.length=a;hc=b}a=hc.shift()}return a},Xa(a,b){null===
b||10===b?(la(S(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(la(S(a.output)),a.output=[])},Db(){return{yb:25856,Ab:5,xb:191,zb:35387,wb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Eb(){return 0},Fb(){return[24,80]}},nc={Xa(a,b){null===b||10===b?(m(S(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(m(S(a.output)),a.output=[])}},U={ya:null,Aa(){return U.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new T(63);U.ya||(U.ya={dir:{node:{Ca:U.ka.Ca,za:U.ka.za,lookup:U.ka.lookup,Qa:U.ka.Qa,rename:U.ka.rename,unlink:U.ka.unlink,rmdir:U.ka.rmdir,readdir:U.ka.readdir,symlink:U.ka.symlink},stream:{xa:U.ma.xa}},file:{node:{Ca:U.ka.Ca,za:U.ka.za},stream:{xa:U.ma.xa,read:U.ma.read,write:U.ma.write,eb:U.ma.eb,gb:U.ma.gb}},link:{node:{Ca:U.ka.Ca,za:U.ka.za,readlink:U.ka.readlink},stream:{}},Za:{node:{Ca:U.ka.Ca,za:U.ka.za},stream:oc}});c=pc(a,b,c,d);16384===(c.mode&61440)?
(c.ka=U.ya.dir.node,c.ma=U.ya.dir.stream,c.ja={}):32768===(c.mode&61440)?(c.ka=U.ya.file.node,c.ma=U.ya.file.stream,c.pa=0,c.ja=null):40960===(c.mode&61440)?(c.ka=U.ya.link.node,c.ma=U.ya.link.stream):8192===(c.mode&61440)&&(c.ka=U.ya.Za.node,c.ma=U.ya.Za.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ja[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Cb(a){return a.ja?a.ja.subarray?a.ja.subarray(0,a.pa):new Uint8Array(a.ja):new Uint8Array(0)},ka:{Ca(a){var b={};b.dev=8192===(a.mode&61440)?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.pa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},za(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.pa!=b&&(0==b?(a.ja=null,a.pa=0):(c=a.ja,a.ja=new Uint8Array(b),c&&
a.ja.set(c.subarray(0,Math.min(b,a.pa))),a.pa=b)))},lookup(){U.Sa||(U.Sa=new T(44),U.Sa.stack="<generic error, no stack>");throw U.Sa;},Qa(a,b,c,d){return U.createNode(a,b,c,d)},rename(a,b,c){try{var d=qc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.ja)throw new T(55);e=rc(d.parent.id,d.name);if(V[e]===d)V[e]=d.Ha;else for(e=V[e];e;){if(e.Ha===d){e.Ha=d.Ha;break}e=e.Ha}}delete a.parent.ja[a.name];b.ja[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,
b){delete a.ja[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=qc(a,b),d;for(d in c.ja)throw new T(55);delete a.ja[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.ja)]},symlink(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},ma:{read(a,b,c,d,e){var f=a.node.ja;if(e>=a.node.pa)return 0;a=Math.min(a.node.pa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},
write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.ja||a.ja.subarray)){if(f)return a.ja=b.subarray(c,c+d),a.pa=d;if(0===a.pa&&0===e)return a.ja=b.slice(c,c+d),a.pa=d;if(e+d<=a.pa)return a.ja.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.ja?a.ja.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.ja,a.ja=new Uint8Array(f),0<a.pa&&a.ja.set(g.subarray(0,a.pa),0));if(a.ja.subarray&&b.subarray)a.ja.set(b.subarray(c,c+d),e);else for(f=0;f<
d;f++)a.ja[e+f]=b[c+f];a.pa=Math.max(a.pa,e+d);return d},xa(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.pa);if(0>b)throw new T(28);return b},eb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.ja;if(e&2||!a||a.buffer!==r.buffer){d=!0;va();e=void 0;if(!e)throw new T(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{na:e,vb:d}},gb(a,b,c,d){U.ma.write(a,b,0,d,
c,!1);return 0}}},sc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},tc=null,uc={},vc=[],wc=1,V=null,xc=!1,yc=!0,zc={},T=class{name="ErrnoError";constructor(a){this.Ga=a}},Ac=class{Na={};node=null;get flags(){return this.Na.flags}set flags(a){this.Na.flags=a}get position(){return this.Na.position}set position(a){this.Na.position=a}},Bc=class{ka={};ma={};Ra=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Aa=a.Aa;this.id=wc++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=
Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function W(a,b={}){if(!a)throw new T(44);b.Ua??(b.Ua=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=tc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=dc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=cc(e+"/"+a[f]);try{d=qc(d,a[f])}catch(h){if(44===h?.Ga&&g&&b.ob)return{path:e};throw h;}!d.Ra||g&&!b.Ua||(d=d.Ra.root);if(40960===(d.mode&61440)&&(!g||b.Ta)){if(!d.ka.readlink)throw new T(52);
d=d.ka.readlink(d);"/"===d.charAt(0)||(d=dc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new T(32);}function rc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%V.length}function qc(a,b){var c=16384===(a.mode&61440)?(c=Cc(a,"x"))?c:a.ka.lookup?0:2:54;if(c)throw new T(c);for(c=V[rc(a.id,b)];c;c=c.Ha){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ka.lookup(a,b)}
function pc(a,b,c,d){a=new Bc(a,b,c,d);b=rc(a.parent.id,a.name);a.Ha=V[b];return V[b]=a}function Dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cc(a,b){if(yc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ec(a,b){if(16384!==(a.mode&61440))return 54;try{return qc(a,b),20}catch(c){}return Cc(a,"wx")}function Fc(a){a=vc[a];if(!a)throw new T(8);return a}
function Gc(a,b){var c=null?.ma.za,d=c?null:a;c??=a.ka.za;if(!c)throw new T(63);c(d,b)}var oc={open(a){a.ma=uc[a.node.rdev].ma;a.ma.open?.(a)},xa(){throw new T(70);}};function kc(a,b){uc[a]={ma:b}}function Hc(a,b){var c="/"===b;if(c&&tc)throw new T(10);if(!c&&b){var d=W(b,{Ua:!1});b=d.path;d=d.node;if(d.Ra)throw new T(10);if(16384!==(d.mode&61440))throw new T(54);}b={type:a,Gb:{},fb:b,nb:[]};a=a.Aa(b);a.Aa=b;b.root=a;c?tc=a:d&&(d.Ra=b,d.Aa&&d.Aa.nb.push(b))}
function Ic(a,b,c){var d=W(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new T(28);if("."===a||".."===a)throw new T(20);var e=Ec(d,a);if(e)throw new T(e);if(!d.ka.Qa)throw new T(63);return d.ka.Qa(d,a,b,c)}function X(a){return Ic(a,16895,0)}function Jc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ic(a,b|8192,c)}
function Kc(a,b){if(!gc(a))throw new T(44);var c=W(b,{parent:!0}).node;if(!c)throw new T(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ec(c,b);if(d)throw new T(d);if(!c.ka.symlink)throw new T(63);c.ka.symlink(c,b,a)}
function Lc(a,b){if(""===a)throw new T(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=W(a,{Ta:!(b&131072),ob:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new T(20);}else{if(e)throw new T(31);d=Ic(a,c|511,0);f=!0}if(!d)throw new T(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new T(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Dc(b)||b&576)?31:Cc(d,Dc(b)):44))throw new T(e);if(b&512&&!f){e=d;e="string"==typeof e?W(e,{Ta:!0}).node:e;if(16384===(e.mode&61440))throw new T(31);if(32768!==(e.mode&61440))throw new T(28);var g=Cc(e,"w");if(g)throw new T(g);Gc(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.Aa.fb;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h={node:d,path:h,flags:b,
seekable:!0,position:0,ma:d.ma,ub:[],error:!1};e=-1;h=Object.assign(new Ac,h);if(-1==e)a:{for(e=0;4096>=e;e++)if(!vc[e])break a;throw new T(33);}h.fd=e;vc[e]=h;h.ma.open&&h.ma.open(h);f&&(c&=511,d="string"==typeof d?W(d,{Ta:!0}).node:d,Gc(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Bb:void 0}));!k.logReadFiles||b&1||a in zc||(zc[a]=1)}function Mc(a,b,c){if(null===a.fd)throw new T(8);if(!a.seekable||!a.ma.xa)throw new T(70);if(0!=c&&1!=c&&2!=c)throw new T(28);a.position=a.ma.xa(a,b,c);a.ub=[]}
function Y(a,b,c){a=cc("/dev/"+a);var d=sc(!!b,!!c);Y.cb??(Y.cb=64);var e=Y.cb++<<8|0;kc(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,p){for(var l=0,n=0;n<p;n++){try{var u=b()}catch(v){throw new T(29);}if(void 0===u&&0===l)throw new T(6);if(null===u||void 0===u)break;l++;g[h+n]=u}l&&(f.node.atime=Date.now());return l},write(f,g,h,p){for(var l=0;l<p;l++)try{c(g[h+l])}catch(n){throw new T(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return l}});Jc(a,d,e)}var Nc={};
(()=>{let a=Sa.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Sa&&c instanceof Sa))return!1;var d=this.ia.oa.la,e=this.ia.na;c.ia=c.ia;var f=c.ia.oa.la;for(c=c.ia.na;d.ta;)e=d.Ma(e),d=d.ta;for(;f.ta;)c=f.Ma(c),f=f.ta;return d===f&&e===c},clone:function(){this.ia.na||Na(this);if(this.ia.La)return this.ia.count.value+=1,this;var c=Qa,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.ia;c=c(e.call(d,f,{ia:{value:{count:g.count,Ka:g.Ka,La:g.La,na:g.na,oa:g.oa,sa:g.sa,va:g.va}}}));
c.ia.count.value+=1;c.ia.Ka=!1;return c},["delete"](){this.ia.na||Na(this);if(this.ia.Ka&&!this.ia.La)throw new J("Object already scheduled for deletion");Pa(this);var c=this.ia;--c.count.value;0===c.count.value&&(c.sa?c.va.Ea(c.sa):c.oa.la.Ea(c.na));this.ia.La||(this.ia.sa=void 0,this.ia.na=void 0)},isDeleted:function(){return!this.ia.na},deleteLater:function(){this.ia.na||Na(this);if(this.ia.Ka&&!this.ia.La)throw new J("Object already scheduled for deletion");Ra.push(this);this.ia.Ka=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(lb.prototype,{lb(a){this.hb&&(a=this.hb(a));return a},$a(a){this.Ea?.(a)},Ba:eb,qa:function(a){function b(){return this.Pa?kb(this.la.Da,{oa:this.pb,na:c,va:this,sa:a}):kb(this.la.Da,{oa:this,na:a})}var c=this.lb(a);if(!c)return this.$a(a),null;var d=ib(this.la,c);if(void 0!==d){if(0===d.ia.count.value)return d.ia.na=c,d.ia.sa=a,d.clone();d=d.clone();this.$a(a);return d}d=this.la.kb(c);d=Ua[d];if(!d)return b.call(this);d=this.Oa?d.ib:d.pointerType;var e=gb(c,this.la,d.la);return null===
e?b.call(this):this.Pa?kb(d.la.Da,{oa:d,na:e,va:this,sa:a}):kb(d.la.Da,{oa:d,na:e})}});V=Array(4096);Hc(U,"/");X("/tmp");X("/home");X("/home/web_user");(function(){X("/dev");kc(259,{read:()=>0,write:(d,e,f,g)=>g,xa:()=>0});Jc("/dev/null",259);jc(1280,mc);jc(1536,nc);Jc("/dev/tty",1280);Jc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(fc(a),b=a.byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Hc({Aa(){var b=pc(a,"fd",16895,73);b.ma={xa:U.ma.xa};b.ka={lookup(c,d){c=+d;var e=Fc(c);c={parent:null,Aa:{fb:"fake"},ka:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(vc.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.noExitRuntime&&(Fa=k.noExitRuntime);k.print&&(la=k.print);k.printErr&&(m=k.printErr);k.wasmBinary&&(q=k.wasmBinary);k.thisProgram&&(da=k.thisProgram);
var qb,Oc,Pc,N,Qc={m:(a,b,c)=>{var d=new Ga(a);E[d.na+16>>2]=0;E[d.na+4>>2]=b;E[d.na+8>>2]=c;Ha=a;Ia++;throw Ha;},F:()=>va(""),k:(a,b,c,d,e)=>{b=G(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}K(a,{name:b,qa:f,ua:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},Ba:Ma(b,c,!d),wa:null})},o:(a,b,c,d)=>{b=G(b);K(a,{name:b,qa:function(e){return!!e},ua:function(e,f){return f?c:d},Ba:function(e){return this.qa(t[e])},wa:null})},l:(a,b,c,d,e,f,g,h,p,l,n,u,v)=>{n=G(n);f=L(e,f);
h&&=L(g,h);l&&=L(p,l);v=L(u,v);var x=Xa(n);Wa(x,function(){O(`Cannot construct ${n} due to unbound types`,[d])});P([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var z=w.la;var A=z.Da}else A=Sa.prototype;w=Ta(n,function(...fb){if(Object.getPrototypeOf(this)!==D)throw new J(`Use 'new' to construct ${n}`);if(void 0===y.Fa)throw new J(`${n} has no accessible constructor`);var ac=y.Fa[fb.length];if(void 0===ac)throw new J(`Tried to invoke ctor of ${n} with invalid number of parameters (${fb.length}) - expected (${Object.keys(y.Fa).toString()}) parameters instead!`);
return ac.apply(this,fb)});var D=Object.create(A,{constructor:{value:w}});w.prototype=D;var y=new Ya(n,w,D,v,z,f,h,l);if(y.ta){var M;(M=y.ta).Ya??(M.Ya=[]);y.ta.Ya.push(y)}z=new lb(n,y,!0,!1,!1);M=new lb(n+"*",y,!1,!1,!1);A=new lb(n+" const*",y,!1,!0,!1);Ua[a]={pointerType:M,ib:A};mb(x,w);return[z,M,A]})},G:(a,b,c,d,e,f)=>{var g=sb(b,c);e=L(d,e);P([],[a],h=>{h=h[0];var p=`constructor ${h.name}`;void 0===h.la.Fa&&(h.la.Fa=[]);if(void 0!==h.la.Fa[b-1])throw new J(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.la.Fa[b-1]=()=>{O(`Cannot construct ${h.name} due to unbound types`,g)};P([],g,l=>{l.splice(1,0,null);h.la.Fa[b-1]=vb(p,l,null,e,f);return[]});return[]})},d:(a,b,c,d,e,f,g,h,p)=>{var l=sb(c,d);b=G(b);b=wb(b);f=L(e,f);P([],[a],n=>{function u(){O(`Cannot call ${v} due to unbound types`,l)}n=n[0];var v=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&n.la.qb.push(b);
var x=n.la.Da,w=x[b];void 0===w||void 0===w.ra&&w.className!==n.name&&w.Ja===c-2?(u.Ja=c-2,u.className=n.name,x[b]=u):(Va(x,b,v),x[b].ra[c-2]=u);P([],l,z=>{z=vb(v,z,n,f,g,p);void 0===x[b].ra?(z.Ja=c-2,x[b]=z):x[b].ra[c-2]=z;return[]});return[]})},h:(a,b,c,d,e,f,g,h,p,l)=>{b=G(b);e=L(d,e);P([],[a],n=>{n=n[0];var u=`${n.name}.${b}`,v={get(){O(`Cannot access ${u} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};v.set=p?()=>O(`Cannot access ${u} due to unbound types`,[c,g]):()=>{throw new J(u+
" is a read-only property");};Object.defineProperty(n.la.Da,b,v);P([],p?[c,g]:[c],x=>{var w=x[0],z={get(){var D=xb(this,n,u+" getter");return w.qa(e(f,D))},enumerable:!0};if(p){p=L(h,p);var A=x[1];z.set=function(D){var y=xb(this,n,u+" setter"),M=[];p(l,y,A.ua(M,D));tb(M)}}Object.defineProperty(n.la.Da,b,z);return[]});return[]})},I:a=>K(a,Bb),j:(a,b,c)=>{b=G(b);K(a,{name:b,qa:d=>d,ua:(d,e)=>e,Ba:Cb(b,c),wa:null})},i:(a,b,c,d,e,f,g)=>{var h=sb(b,c);a=G(a);a=wb(a);e=L(d,e);Wa(a,function(){O(`Cannot call ${a} due to unbound types`,
h)},b-1);P([],h,p=>{p=[p[0],null].concat(p.slice(1));mb(a,vb(a,p,null,e,f,g),b-1);return[]})},c:(a,b,c,d,e)=>{b=G(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}K(a,{name:b,qa:f,ua:(h,p)=>p,Ba:Ma(b,c,0!==d),wa:null})},a:(a,b,c)=>{function d(f){return new e(r.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=G(c);K(a,{name:c,qa:d,Ba:d},{mb:!0})},H:a=>{K(a,Db)},n:(a,b)=>{b=G(b);
K(a,{name:b,qa(c){var d=(d=c+4)?S(t,d,E[c>>2],!0):"";N(c);return d},ua(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new J("Cannot pass non-string to std::string");var f=e?Eb(d):d.length;var g=Pc(4+f+1),h=g+4;E[g>>2]=f;e?R(d,t,h,f+1):t.set(d,h);null!==c&&c.push(N,g);return g},Ba:eb,wa(c){N(c)}})},e:(a,b,c)=>{c=G(c);if(2===b){var d=Ib;var e=Jb;var f=Kb}else d=Lb,e=Mb,f=Nb;K(a,{name:c,qa:g=>{var h=d(g+4,E[g>>
2]*b,!0);N(g);return h},ua:(g,h)=>{if("string"!=typeof h)throw new J(`Cannot pass non-string to C++ string type ${c}`);var p=f(h),l=Pc(4+p+b);E[l>>2]=p/b;e(h,l+4,p+b);null!==g&&g.push(N,l);return l},Ba:eb,wa(g){N(g)}})},p:(a,b)=>{b=G(b);K(a,{bb:!0,name:b,qa:()=>{},ua:()=>{}})},t:()=>{Fa=!1;Ob=0},x:(a,b,c)=>{var [d,...e]=Rb(a,b);b=d.ua.bind(d);var f=e.map(p=>p.Ba.bind(p));a--;var g={toValue:Ab};a=f.map((p,l)=>{var n=`argFromPtr${l}`;g[n]=p;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var h=
"toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Ub,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.bb||(g.toReturnWire=b,g.emval_returnValue=Sb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;return Qb(Ta(h,c))},r:(a,b,
c,d,e)=>Pb[a](b,c,d,e),q:a=>{var b=Ab(a);tb(b);zb(a)},u:(a,b)=>{Vb[a]&&(clearTimeout(Vb[a].id),delete Vb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Vb[a];Xb(()=>Oc(a,performance.now()))},b);Vb[a]={id:c,Hb:b};return 0},v:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);C[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,
"0")}`};a=b(f);b=b(e);e<f?(R(a,t,c,17),R(b,t,d,17)):(R(a,t,d,17),R(b,t,c,17))},b:()=>Date.now(),g:a=>m(a?S(t,a):""),f:()=>performance.now(),y:()=>{va("OOM")},D:(a,b)=>{var c=0,d=0,e;for(e of $b()){var f=b+c;E[a+d>>2]=f;c+=R(e,t,f,Infinity)+1;d+=4}return 0},E:(a,b)=>{var c=$b();E[a>>2]=c.length;a=0;for(var d of c)a+=Eb(d)+1;E[b>>2]=a;return 0},B:function(a){try{var b=Fc(a);if(null===b.fd)throw new T(8);b.Va&&(b.Va=null);try{b.ma.close&&b.ma.close(b)}catch(c){throw c;}finally{vc[b.fd]=null}b.fd=null;
return 0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;return c.Ga}},w:function(a,b,c,d){try{a:{var e=Fc(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],p=E[a+4>>2];a+=8;var l=e,n=h,u=p,v=f,x=r;if(0>u||0>v)throw new T(28);if(null===l.fd)throw new T(8);if(1===(l.flags&2097155))throw new T(8);if(16384===(l.node.mode&61440))throw new T(31);if(!l.ma.read)throw new T(28);var w="undefined"!=typeof v;if(!w)v=l.position;else if(!l.seekable)throw new T(70);var z=l.ma.read(l,x,n,u,v);w||(l.position+=
z);var A=z;if(0>A){var D=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&(f+=A)}D=b}E[d>>2]=D;return 0}catch(y){if("undefined"==typeof Nc||"ErrnoError"!==y.name)throw y;return y.Ga}},A:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Fc(a);Mc(e,b,c);sa[d>>3]=BigInt(e.position);e.Va&&0===b&&0===c&&(e.Va=null);return 0}catch(f){if("undefined"==typeof Nc||"ErrnoError"!==f.name)throw f;return f.Ga}},C:function(a,b,c,d){try{a:{var e=Fc(a);a=
b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],p=E[a+4>>2];a+=8;var l=e,n=h,u=p,v=f,x=r;if(0>u||0>v)throw new T(28);if(null===l.fd)throw new T(8);if(0===(l.flags&2097155))throw new T(8);if(16384===(l.node.mode&61440))throw new T(31);if(!l.ma.write)throw new T(28);l.seekable&&l.flags&1024&&Mc(l,0,2);var w="undefined"!=typeof v;if(!w)v=l.position;else if(!l.seekable)throw new T(70);var z=l.ma.write(l,x,n,u,v,void 0);w||(l.position+=z);var A=z;if(0>A){var D=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&
(f+=A)}D=b}E[d>>2]=D;return 0}catch(y){if("undefined"==typeof Nc||"ErrnoError"!==y.name)throw y;return y.Ga}},s:Wb,z:function(a,b){try{return fc(t.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Nc||"ErrnoError"!==c.name)throw c;return c.Ga}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.J;c=oa.buffer;r=new Int8Array(c);pa=new Int16Array(c);t=new Uint8Array(c);B=new Uint16Array(c);C=new Int32Array(c);E=new Uint32Array(c);qa=new Float32Array(c);ra=new Float64Array(c);sa=new BigInt64Array(c);ta=new BigUint64Array(c);ob=Z.P;c=Z;qb=c.L;k.__ZdlPvm=c.M;Oc=c.N;Pc=c.O;k._strndup=c.Q;k.__ZdaPv=c.R;k.__ZdaPvm=c.S;k.__ZdlPv=c.T;k._emscripten_builtin_malloc=c.U;k.__Znaj=c.V;k.__ZnajSt11align_val_t=c.W;k.__Znwj=c.X;k.__ZnwjSt11align_val_t=c.Y;k.___libc_calloc=
c.Z;k.___libc_free=c._;k.___libc_malloc=c.$;k.___libc_realloc=c.aa;k._emscripten_builtin_calloc=c.ba;k._emscripten_builtin_free=c.ca;k._emscripten_builtin_realloc=c.da;N=c.ea;k._malloc_size=c.fa;k._malloc_usable_size=c.ga;k._reallocf=c.ha;F--;k.monitorRunDependencies?.(F);0==F&&ua&&(c=ua,ua=null,c());return Z}F++;k.monitorRunDependencies?.(F);var b={a:Qc};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});wa??=k.locateFile?k.locateFile("hillclimbing.wasm",ha):ha+
"hillclimbing.wasm";return a((await za(b)).instance)})();
function Rc(){function a(){k.calledRun=!0;if(!ma){if(!k.noFSInit&&!xc){var b,c;xc=!0;b??=k.stdin;c??=k.stdout;d??=k.stderr;b?Y("stdin",b):Kc("/dev/tty","/dev/stdin");c?Y("stdout",null,c):Kc("/dev/tty","/dev/stdout");d?Y("stderr",null,d):Kc("/dev/tty1","/dev/stderr");Lc("/dev/stdin",0);Lc("/dev/stdout",1);Lc("/dev/stderr",1)}Z.K();yc=!1;k.onRuntimeInitialized?.();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var d=k.postRun.shift();Ca.push(d)}Ba(Ca)}}if(0<
F)ua=Rc;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ea();Ba(Da);0<F?ua=Rc:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);a()},1)):a()}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();Rc();
